### ISSUE TITLE
Compatible with VideoJS 7.0?

### ISSUE THREAD

**Issue by thekendog** [videojs/videojs-flash#76] opened 2018-07-05 13:34 UTC
Is this compatible with 7.0?  I had this working with version 6 of VideoJS but I just updated to 7 and the fallback isn't working in IE11 on Windows 7 anymore.  I'm trying to play an HLS stream.

**Comment by gkatsev** [comment] 2018-07-05 14:59
It is compatible, though, if you're using a bundler it may be end up not working because of the dependency version. It'll be fixed by https://github.com/videojs/videojs-flash/pull/75

**Closed** 2018-07-05 15:07 UTC

**Comment by gkatsev** [comment] 2018-07-05 15:22
Published as 2.1.1.

**Comment by thekendog** [comment] 2018-07-05 15:36
After testing this I figured out the issue, it does not work with the new VideoJS HTTP Streaming plugin which is bundled by default in 7.  I had to use the core version and then add the contrib-hls plugin.

**Comment by gkatsev** [comment] 2018-07-05 15:39
Oh, I wonder if VHS is trying to bind to flash but flash is loaded later so it can't.

**Comment by forbesjo** [comment] 2018-07-05 15:43
VHS does not include flash support, you'll have to use flashls for videojs-contrib-hls

**Comment by thekendog** [comment] 2018-07-05 16:03
@forbesjo I tried that too, I keep getting an "Unable to get property 'registerSourceHandler' of undefined or null reference" error.

**Comment by forbesjo** [comment] 2018-07-05 17:15
Did you also include this project in your page as well? The flashls registers to the flash tech here https://github.com/brightcove/videojs-flashls-source-handler/blob/master/src/index.js#L571 and you'll see that error if videojs-flash is missing

**Comment by thekendog** [comment] 2018-07-05 17:40
I did, here's a test page.

http://www.resortcams.com/videojs/flash.php

**Comment by forbesjo** [comment] 2018-07-05 17:56
Try this http://jsbin.com/sejogam/edit?html,js. I believe the problem is that the player is being instantiated before the swf is set, so instead the player is using the default swf which does not have HLS support. If this works for you I'll update the flashls source handler documentation for clarity.

**Comment by thekendog** [comment] 2018-07-05 17:57
Yes, that works!  Thanks for the help!

**Comment by gaxunil** [comment] 2018-08-21 22:02
So just to be totally clear - for VideoJS 7 to get HLS working with flash, we need to bring in both videojs-flash AND /videojs-flashls-source-handler ?

**Comment by forbesjo** [comment] 2018-08-22 15:10
That's correct

**Comment by gaxunil** [comment] 2018-08-22 15:46
Thank you!!
